### ISSUE TITLE
Undeclared variable in the vesting example

### ISSUE THREAD

**Issue by trevinwisaksana** [aiken-lang/site#16]
#### Describe what the problem is?

There is an undeclared variable in the `vesting_unlock.ts` script that can be found in the vesting example shown [here](https://aiken-lang.org/getting-started/vesting). The variable `using` in the `unlock` function is not declared.

#### What should be the expected behavior?

Based on the Lucid documentation, `collectFrom`'s second argument expects a redeemer. So I believe the code below should work.

```
async function unlock(ref, { from, redeemer }): Promise<TxHash> {
  const [utxo] = await lucid.utxosByOutRef([ref]);
 
  const currentTime = new Date().getTime();
  const laterTime = new Date(currentTime + 2 * 60 * 60 * 1000); // add two hours (TTL: time to live)
 
  const tx = await lucid
    .newTx()
    .collectFrom([utxo], redeemer) // <-- fixed here
    .addSigner(await lucid.wallet.address()) // this should be beneficiary address
    .validFrom(currentTime)
    .validTo(laterTime)
    .attachSpendingValidator(from)
    .complete();
 
  const signedTx = await tx
    .sign()
    .complete();
 
  return signedTx.submit();
}
```

**Comment by KtorZ** [comment]
Nice catch, thank you! We'll fix ASAP (I'd like to re-run the tutorial to make sure we didn't miss anything else).

**Comment by rvcas** [comment]
Closed by

https://github.com/aiken-lang/site/pull/17
