### ISSUE TITLE
Documentation gets wrong type signatures of some of the builtins

### ISSUE THREAD

**Issue by effectfully** [aiken-lang/site#19]
#### Describe what the problem is? 

At least these two are wrong in the [documentation](https://aiken-lang.org/uplc/builtins#user-content-fnref-3):

```
mkNilData | (α) | (unit) | list (α)
mkPairData | (α, β) | ((α), (β)) | pair (α) (β)
```

Plus `mkNilPairData` seems to be entirely missing.

#### What should be the expected behavior?

Type signatures should agree with the output of `cabal run uplc print-builtin-signatures`.

In particular for the two mentioned builtins:

```
mkNilData | - | (unit) | list (data)
mkPairData | - | (data, data) | pair (data) (data)
```

**Comment by rvcas** [comment]
Only thing left is to add mkNilPairData
