### ISSUE TITLE
Feedback for “Vesting”

### ISSUE THREAD

**Issue by wailokmonad** [aiken-lang/site#35]
After reviewing the codebase and trying on preprod-testnet myself, i would like to suggest the following minor improvement:

Instead of typing the txHash ourself and claiming just one vesting at a time, we should query all the UTXOs from the script address and do a simple filtering based on caller's publicKeyHash and datum's lock_until, and feed all the matching UTXOs to the TX.

```
let now = Date.now()

const scriptUtxos = await lucid.utxosAt(scriptAddress);

let utxos = scriptUtxos.filter((utxo) => {

        let datum = Data.from<Datum>(
            utxo.datum,
            Datum,
        );

        return datum.beneficiary === beneficiaryPublicKeyHash && datum.lock_until <= now;
});

if(utxos.length === 0) { console.log("no utxo found"); return; }

const txUnlock = await unlock(utxos, { from: validator, redeemer:Data.empty() });

async function unlock(utxos, { from, redeemer }): Promise<TxHash> {

        const tx = await lucid
          .newTx()
          .collectFrom(utxos, redeemer)

       // same logic here

```

Thanks for you guys contribution!

**Comment by KtorZ** [comment]
I like the idea! @wailokmonad are you willing to issue a PR to make this happen?

**Comment by wailokmonad** [comment]
Sure, i will

**Comment by wailokmonad** [comment]
PR created. Please review. 

Btw, i was planning to add a new topic based on [this](https://plutus-pioneer-program.readthedocs.io/en/latest/pioneer/week1.html)
