### ISSUE TITLE
Cannot convert undefined to a BigInt

### ISSUE THREAD

**Issue by ReddSpark1** [aiken-lang/site#37]
#### What operating system are you using, and which version?

- [X ] Windows 11,

#### Describe what the problem is? 
I am runnining through the Hello world tutorial and got to the point where I run `deno run --allow-net --allow-read --allow-env hello_world-lock.ts` however this is throwing up the error:

```
Uncaught (in promise) TypeError: Cannot convert undefined to a BigInt
      keyDeposit: BigInt(result.key_deposit),
                  ^
    at BigInt (<anonymous>)
    at Blockfrost.getProtocolParameters (https://deno.land/x/lucid@0.8.3/src/provider/blockfrost.ts:38:19)
    at async Function.new (https://deno.land/x/lucid@0.8.3/src/lucid/lucid.ts:52:34)
    at async file:///D:/aiken/hello_world/hello_world-lock.ts:15:15
PS D:\aiken\hello_world> deno run --allow-net --allow-read --allow-env hello_world-lock.ts
error: Uncaught (in promise) TypeError: Cannot convert undefined to a BigInt
      keyDeposit: BigInt(result.key_deposit),
                  ^
    at BigInt (<anonymous>)
    at Blockfrost.getProtocolParameters (https://deno.land/x/lucid@0.8.3/src/provider/blockfrost.ts:38:19)
    at async Function.new (https://deno.land/x/lucid@0.8.3/src/lucid/lucid.ts:52:34)
    at async file:///D:/aiken/hello_world/hello_world-lock.ts:15:15
```

Row 15 of the hello_world-lock.ts file points to:
```
const lucid = await Lucid.new(
  new Blockfrost(
    "https://cardano-preview.blockfrost.io/api/v0",
    Deno.env.get("XXXX")
  ),
  "Preview"
```
);

Someone else has checked the Blockfrost API key and it appears to work fine for them.

#### What should be the expected behavior?
`1 tADA locked into the contract at: ...`

**Comment by KtorZ** [comment]
Added some notice to the tutorial:

<img width="918" alt="Screenshot 2023-04-20 at 17 46 45" src="https://user-images.githubusercontent.com/5680256/233419517-d46e5947-cc27-4d96-81e9-2f4bc30a867c.png">
