### ISSUE TITLE
Assign name to list's rest in a pattern match

### ISSUE THREAD

**Issue by KristianBalaj** [aiken-lang/site#50]
### What is your idea? Provide a use case.

I'm not sure how to pattern match the list's rest.
Having the following code:
```aiken
when foo is {
   [a, ..] -> todo // I want to use `..` here
   _ -> False
}
```

How to use the `..` in some additional logic based on the pattern match?

I would imagine something like this:
```aiken
when foo is {
   [a, .. as xs] -> bar(xs)
   _ -> False
}
```

But that's not possible.

### What is the current alternative and why is it not good enough?

Well I could do the following as a workaround:

```aiken
when foo is {
   [a, ..] -> when list.tail(foo) is {
      Some(b) -> bar(b)
      _ -> False
   }
   _ -> False
}
```

But I don't like it since it's too verbose and includes an additional pattern match that adds more nesting.

**Comment by KtorZ** [comment]
You mean a whole section like: https://aiken-lang.org/language-tour/control-flow#matching 😅  ?

**Comment by rvcas** [comment]
closing cause it's in the docs and this issue has just been sitting here and there's not really anything to action on
