### ISSUE TITLE
Documentation uses module cardano/transaction/value

### ISSUE THREAD

**Issue by JustLeif** [aiken-lang/site#89]
# First

**Thank you very much for your work on Aiken. It cannot be stated how much I appreciate you trying to make development on Cardano more approachable.**

## Describe what the problem is? 
The documentation for the gift card example uses a module that doesn't appear in the newest version of the standard library. 

<img width="1186" alt="Screenshot 2024-11-02 at 11 47 47" src="https://github.com/user-attachments/assets/45bf886b-db5f-49c5-a1c4-d43284e28d5b">
<img width="626" alt="Screenshot 2024-11-02 at 11 47 36" src="https://github.com/user-attachments/assets/32eb3463-3d73-4706-8938-c6f7df9f13eb">
<img width="257" alt="Screenshot 2024-11-02 at 11 51 06" src="https://github.com/user-attachments/assets/44fdf123-108d-468d-8b76-05cb20c3ff1a">

## What should be the expected behavior?
I assume there is a new module or function that replaces the logic of the `value.from_minted_value` & `value.tokens(policy_id)`? I would offer a PR to fix this issue, but I'm very new to Cardano smart contract development and not sure if it is even an issue or maybe I made a mistake.

**Comment by JustLeif** [comment]
> Hello @JustLeif , yupp i was also facing the same issue. In the new version of AIKEN we can use cardano/assets, and we can remove the line " value.from_minted_value ". and also my PR is merged and the Gift Card example is now working good. please check the doc of gift card again, Thank You.

Awesome thanks!

**Comment by speedlightwp** [comment]
Hi, when running the aiken check. I encountered the following error. 

let Transaction { mint, inputs, .. } = transaction
    ·                                            ─────┬─────
    ·                                                 ╰── unknown variable


<img width="641" alt="Screenshot 2024-11-13 at 11 50 07 AM" src="https://github.com/user-attachments/assets/5fc87a20-4458-4647-b0f6-ec98a9591538">

**Comment by JustLeif** [comment]
> Hi, when running the aiken check. I encountered the following error.
> 
> let Transaction { mint, inputs, .. } = transaction · ─────┬───── · ╰── unknown variable
> <img alt="Screenshot 2024-11-13 at 11 50 07 AM" width="641" src="https://private-user-images.githubusercontent.com/51754027/385577910-5fc87a20-4458-4647-b0f6-ec98a9591538.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0NzA1MTYsIm5iZiI6MTczMTQ3MDIxNiwicGF0aCI6Ii81MTc1NDAyNy8zODU1Nzc5MTAtNWZjODdhMjAtNDQ1OC00NjQ3LWIwZjYtZWM5OGE5NTkxNTM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDAzNTY1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiY2ViZmM2MDQxZDVjMGI3MjU3ZjZkZDY3MWI4NjlhZjc4YzNlYjUwNTNhMzQwODQyOTZhZThkNTQ3MDlkOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.kQxW2B3lzSYnEhMoWX66nwtcr35zXilFwsv0vGQoIho">

I believe that you are referencing the variable you defined as 'tx'. Try using this:

```
let Transaction { mint, inputs, .. } = tx
```

**Comment by speedlightwp** [comment]
I tried that too. This is the error:

<img width="799" alt="Screenshot 2024-11-13 at 11 59 59 AM" src="https://github.com/user-attachments/assets/bac9382c-db4f-4825-8ab5-61a058284971">

**Comment by speedlightwp** [comment]
First time testing out Aiken. I guess the the website examples need further updates and testing.

**Comment by FaizanShaikh-3033** [comment]
> I tried that too. This is the error:
> 
> <img alt="Screenshot 2024-11-13 at 11 59 59 AM" width="799" src="https://private-user-images.githubusercontent.com/51754027/385579735-bac9382c-db4f-4825-8ab5-61a058284971.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0NzA4OTMsIm5iZiI6MTczMTQ3MDU5MywicGF0aCI6Ii81MTc1NDAyNy8zODU1Nzk3MzUtYmFjOTM4MmMtZGI0Zi00ODI1LThhYjUtNjFhMDU4Mjg0OTcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDA0MDMxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3MWE5NGRiZTIwNmI5M2MyYjA5MmRiZGNjNTkxOGM4NTQ1ZmU0ODEzYjhlZmY2YjhlYjZkNWMwNmUzYjYwMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.h1CBf1t4vMbslg_9_235bg4lN6qSRg-p-KUBbou-DIk">

hello @speedlightwp thanks for bringing this up,
that should be like _d: Option<Data> 
thanks for pointing out my mistake,
will solve it quickly

**Comment by JustLeif** [comment]
> I tried that too. This is the error:
> <img alt="Screenshot 2024-11-13 at 11 59 59 AM" width="799" src="https://private-user-images.githubusercontent.com/51754027/385579735-bac9382c-db4f-4825-8ab5-61a058284971.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0NzExNzQsIm5iZiI6MTczMTQ3MDg3NCwicGF0aCI6Ii81MTc1NDAyNy8zODU1Nzk3MzUtYmFjOTM4MmMtZGI0Zi00ODI1LThhYjUtNjFhMDU4Mjg0OTcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDA0MDc1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3MWM5ZGFhNjQ4OGNhODc4NTI5YjY4YTFlZDVkM2IxZGY2ZTM2MTE3N2Y1OTYyNWU3ZmYwNDNmZWUyMmM0ZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.800b_OkWV3R7spOWWRPHd4h5rJR3am72wzjqpvueE5A">

For this error, change the type of Data to be:

```
_d: Option<Data>
```

instead of

```
_d: Data
```

I'm actually working on a course right now to write Aiken smart contracts and use them with the MeshSDK, the first project will be a demo bank. I can send you the videos when I'm done with them if you want :)

**Comment by speedlightwp** [comment]
Hi JustLeif, thank you. Do send me the videos once you have done. I am new to Aiken smart contracts, would like to learn more about it too.

**Comment by KtorZ** [comment]
Note: the gift_card tutorial is indeed lacking a bit behind. You can see the ongoing PR #96 updating it. We'll be wrapping this up in the upcoming days.
