### ISSUE TITLE
Feedback for “Command-line utilities”

### ISSUE THREAD

**Issue by abailly** [aiken-lang/site#9]
I find the use of the term `bytecode` to describe the `flat` encoding of UPLC confusing: It's not bytecode, it's just binary encoding of the UPLC program into some specific format (eg. flat encoding). The term _bytecode_ should be reserved to describe instruction sets for virtual machine. This is important because whereas a bytecode-encoded program can be interpreted (or rather executed) directly, using raw bytes, against some VM "architecture", a serialised program needs first to be deserialised to be interpreted.

**Comment by rvcas** [comment]
I agree, let's get that fixed. Thanks for the feedback.
